### Question 1

In [11]:
import numpy as np

A = np.zeros((4, 4))
A[0, :] = [1, 1, 1, 1]
A[1, :] = [-0.45, 0.55, 0, 0]
A[2, :] = [0, 1, 0, 0]
A[3, :] = [0.14, 0.2, 0.2, 0.1]
A

array([[ 1.  ,  1.  ,  1.  ,  1.  ],
       [-0.45,  0.55,  0.  ,  0.  ],
       [ 0.  ,  1.  ,  0.  ,  0.  ],
       [ 0.14,  0.2 ,  0.2 ,  0.1 ]])

In [12]:
b = np.array([250, 0, 62.5, 37.5])
b

array([250. ,   0. ,  62.5,  37.5])

In [13]:
np.linalg.solve(A, b)

array([76.38888889, 62.5       , 31.94444444, 79.16666667])

### Question 2

In [35]:
y = [-45, -3, -31, -45, 18, 8, 20, 2, -27, -38]
X = np.zeros((10, 5))

In [36]:
X[0, :] = [1, -1, 0, 0, 0]
X[1, :] = [1, 0, -1, 0, 0]
X[2, :] = [1, 0, 0, -1, 0]
X[3, :] = [1, 0, 0, 0, -1]
X[4, :] = [0, 1, -1, 0, 0]
X[5, :] = [0, 1, 0, -1, 0]
X[6, :] = [0, 1, 0, 0, -1]
X[7, :] = [0, 0, 1, -1, 0]
X[8, :] = [0, 0, 1, 0, -1]
X[9, :] = [0, 0, 0, 1, -1]

X

array([[ 1., -1.,  0.,  0.,  0.],
       [ 1.,  0., -1.,  0.,  0.],
       [ 1.,  0.,  0., -1.,  0.],
       [ 1.,  0.,  0.,  0., -1.],
       [ 0.,  1., -1.,  0.,  0.],
       [ 0.,  1.,  0., -1.,  0.],
       [ 0.,  1.,  0.,  0., -1.],
       [ 0.,  0.,  1., -1.,  0.],
       [ 0.,  0.,  1.,  0., -1.],
       [ 0.,  0.,  0.,  1., -1.]])

In [37]:
M = X.T @ X

M

array([[ 4., -1., -1., -1., -1.],
       [-1.,  4., -1., -1., -1.],
       [-1., -1.,  4., -1., -1.],
       [-1., -1., -1.,  4., -1.],
       [-1., -1., -1., -1.,  4.]])

In [38]:
p = X.T @ y

p

array([-124.,   91.,  -40.,  -17.,   90.])

In [39]:
M[4, :] = [1, 1, 1, 1, 1]
p[4] = 0

In [40]:
print(M)
print()
print(p)

[[ 4. -1. -1. -1. -1.]
 [-1.  4. -1. -1. -1.]
 [-1. -1.  4. -1. -1.]
 [-1. -1. -1.  4. -1.]
 [ 1.  1.  1.  1.  1.]]

[-124.   91.  -40.  -17.    0.]


In [47]:
r = M.T @ p

r

array([-530.,  545., -110.,    5.,   90.])

### Question 3

In [ ]:
def lehmer_entry(rows, columns):
    
    # generate empty matrix
    A = np.zeros((rows, columns))
    
    for i in range(len(A)):
        for j in range(len(A)): 
            
            #set diagonals, only works for even matrices
            if j==i:
                A[i][j] = 1
            
            # add 1 to all values so we don't divide by zero
            elif j > i:
                A[i][j] = (i+1)/(j+1)
            else:
                A[i][j] = (j+1)/(i+1)
    return A
    
A = lehmer_entry(20, 20)
print(A)
print()
print()
# yes, it is symmetrical
print(A[0, :])
print(A[:, 0])

[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111 0.1        0.09090909 0.08333333
  0.07692308 0.07142857 0.06666667 0.0625     0.05882353 0.05555556
  0.05263158 0.05      ]
 [0.5        1.         0.66666667 0.5        0.4        0.33333333
  0.28571429 0.25       0.22222222 0.2        0.18181818 0.16666667
  0.15384615 0.14285714 0.13333333 0.125      0.11764706 0.11111111
  0.10526316 0.1       ]
 [0.33333333 0.66666667 1.         0.75       0.6        0.5
  0.42857143 0.375      0.33333333 0.3        0.27272727 0.25
  0.23076923 0.21428571 0.2        0.1875     0.17647059 0.16666667
  0.15789474 0.15      ]
 [0.25       0.5        0.75       1.         0.8        0.66666667
  0.57142857 0.5        0.44444444 0.4        0.36363636 0.33333333
  0.30769231 0.28571429 0.26666667 0.25       0.23529412 0.22222222
  0.21052632 0.2       ]
 [0.2        0.4        0.6        0.8        1.         0.83333333
  0.71428571 0.625      0.555

In [ ]:
C = np.linalg.inv(A)
d = [1, 2, 3, 4, 5, 
     6, 7, 8, 9, 10, 
     10, 9, 8, 7, 6, 
     5, 4, 3, 2, 1]

### Question 4

In [62]:
x = np.linalg.solve(A, C@d)
x[9]

20.064239273130674