In [1]:
import numpy as np
import gurobipy as gp

### Question 1

In [7]:
obj = np.array([4, 5])

A = np.zeros((2, 2))

A[0, :] = [2, 3]
A[1, :] = [1, -1]

b = np.array([60, 0])
sense = np.array(['<', '<'])

In [8]:
# create empty model
model = gp.Model()

# set num of vars
modelVar = model.addMVar(2)

# set constraints
modelCon = model.addMConstrs(A, modelVar, sense, b)
model.setMObjective(None, obj, 0, sense = gp.GRB.MAXIMIZE)

model.Params.OutputFlag = 0
model.Params.TimeLimit = 3600

In [9]:
model.optimize()

In [10]:
model.objVal

108.0

In [24]:
modelVar.x

array([12., 12.])

### Question 2

In [87]:
# set objective vector
obj = np.array([2000, 3000])

# initialize constraint matrix
A = np.zeros((3, 2))

A[0, :] = [1, 1] # acre constraint
A[1, :] = [3, 2] # worker constraint
A[2, :] = [2, 4] # fertilizer constaint

b = np.array([450, 1000, 1800])
sense = np.array(['<', '<', '<'])

In [88]:
# create empty model
model = gp.Model()

# set num of vars
modelVar = model.addMVar(2)

# set constraints
modelCon = model.addMConstrs(A, modelVar, sense, b)
model.setMObjective(None, obj, 0, sense = gp.GRB.MAXIMIZE)

model.Params.OutputFlag = 0
model.Params.TimeLimit = 3600

In [89]:
# solve
model.optimize()

In [90]:
model.objVal

1350000.0

In [91]:
modelVar.x

array([  0., 450.])

Let me try something cleaner...

In [14]:
# set objective vector
obj = np.array([2000, 3000])

# initialize constraint matrix
A = np.zeros((3, 2))

A[0, :] = [1, 1] # acre constraint
A[1, :] = [3, 2] # worker constraint
A[2, :] = [2, 4] # fertilizer constaint

sense = np.array(['<', '<', '<'])
fert = list(range(200, 2300, 100)) # create whole range of fertilizer constraints

In [18]:
for i in fert:
    b = np.array([450, 1000, i])

    # create empty model
    model = gp.Model()

    # set num of vars
    modelVar = model.addMVar(2)

    # set constraints
    modelCon = model.addMConstrs(A, modelVar, sense, b)
    model.setMObjective(None, obj, 0, sense = gp.GRB.MAXIMIZE)

    model.Params.OutputFlag = 0
    model.Params.TimeLimit = 3600

    # solve
    model.optimize()

    # look for instances of 0 acres allocated to corn
    if modelVar.x[0] == 0:

        print('Fertilizer constraint: ', i)
        print('Allocation: ', modelVar.x)
        break
    

Fertilizer constraint:  1800
Allocation:  [  0. 450.]


### Question 3

In [19]:
obj = np.array([13, 16, 16, 14, 39])

A = np.zeros((7, 5))

A[0, :] = [11, 53, 5, 5, 29]
A[1, :] = [3, 6, 5, 1, 34]
A[2, :] = [1, 0, 0, 0, 0]
A[3, :] = [0, 1, 0, 0, 0]
A[4, :] = [0, 0, 1, 0, 0]
A[5, :] = [0, 0, 0, 1, 0]
A[6, :] = [0, 0, 0, 0, 1]

b = np.array([40, 20, 1, 1, 1, 1, 1])
sense = np.array(['<', '<', '<', '<', '<', '<', '<'])

In [20]:
# create empty model
model = gp.Model()

# set num of vars
modelVar = model.addMVar(5)

# set constraints
modelCon = model.addMConstrs(A, modelVar, sense, b)
model.setMObjective(None, obj, 0, sense = gp.GRB.MAXIMIZE)

model.Params.OutputFlag = 0
model.Params.TimeLimit = 3600


In [21]:
model.optimize()

In [22]:
model.objVal

57.449017199017206

In [23]:
modelVar.x

array([1.        , 0.20085995, 1.        , 1.        , 0.28808354])

### Question 4

In [95]:
obj = np.array([0.18, 0.23, 0.05])

A = np.zeros((7, 3))

A[0, :] = [72, 121, 65]
A[1, :] = [72, 121, 65]
A[2, :] = [107, 500, 0]
A[3, :] = [107, 500, 0]
A[4, :] = [1, 0, 0]
A[5, :] = [0, 1, 0]
A[6, :] = [0, 0, 1]

b = np.array([2000, 2250, 5000, 50000, 10, 10, 10])

sense = np.array(['>', '<', '>', '<', '<', '<', '<'])

In [96]:
# create empty model
model = gp.Model()

# set num of vars
modelVar = model.addMVar(3)

# set constraints
modelCon = model.addMConstrs(A, modelVar, sense, b)
model.setMObjective(None, obj, 0, sense = gp.GRB.MINIMIZE)

model.Params.OutputFlag = 0
model.Params.TimeLimit = 3600

In [97]:
model.optimize()

In [98]:
model.objVal

3.1500000000000004

In [99]:
modelVar.x

array([ 1.94444444, 10.        , 10.        ])

### Question 5

In [110]:
obj = np.array([2, 2.6, 2.8, 3, 3.6, 4.8])

A = np.zeros((6, 6))

A[0, :] = [1, 1, 0, 0, 0 , 0]
A[1, :] = [0, 0, 1.3, 1.2, 0, 0]
A[2, :] = [0, 0, 0, 0, 1.4, 1.6]
A[3, :] = [1, 1, 0, 0, 0 , 0]
A[4, :] = [0, 0, 1.3, 1.2, 0, 0]
A[5, :] = [0, 0, 0, 0, 1.4, 1.6]


b = np.array([1.2, 1.5, 2, 2, 2, 3])
sense = np.array(['>', '>', '>', '<', '<', '<'])

In [111]:
# create empty model
model = gp.Model()

# set num of vars
modelVar = model.addMVar(6)

# set constraints
modelCon = model.addMConstrs(A, modelVar, sense, b)
model.setMObjective(None, obj, 0, sense = gp.GRB.MAXIMIZE)

model.Params.OutputFlag = 0
model.Params.TimeLimit = 3600

In [112]:
model.optimize()

In [113]:
model.objVal

19.2

In [114]:
model.x

[0.0, 2.0, 0.0, 1.6666666666666667, 0.0, 1.875]